"""Immutable package constants."""

SCHEMA_VERSION = "1.0.0"
DEFAULT_TIMEOUT_S = 300
DEFAULT_CHECK_TIMEOUT_S = 60
DEFAULT_STDIO_TAIL_BYTES = 4000
DEFAULT_PARALLEL = 4
DEFAULT_BASE_SEED = 42
MAX_CHECKS_PER_TASK = 20
HIDDEN_PREFIX = "_fsbench_hidden_"
RUNS_DATABASE_NAME = "runs.sqlite"
HARNESS_LOG_NAME = "harness.log"
